export interface JobSpyCountry {
    indeedDomain: string;
    indeedCountryCode: string;
    glassdoorDomain?: string;
}

const COUNTRY_MAP: Record<string, JobSpyCountry> = {
    argentina: { indeedDomain: 'ar', indeedCountryCode: 'AR', glassdoorDomain: 'www.glassdoor.com.ar' },
    australia: { indeedDomain: 'au', indeedCountryCode: 'AU', glassdoorDomain: 'www.glassdoor.com.au' },
    austria: { indeedDomain: 'at', indeedCountryCode: 'AT', glassdoorDomain: 'www.glassdoor.at' },
    bahrain: { indeedDomain: 'bh', indeedCountryCode: 'BH' },
    bangladesh: { indeedDomain: 'bd', indeedCountryCode: 'BD' },
    belgium: { indeedDomain: 'be', indeedCountryCode: 'BE', glassdoorDomain: 'fr.glassdoor.be' },
    brazil: { indeedDomain: 'br', indeedCountryCode: 'BR', glassdoorDomain: 'www.glassdoor.com.br' },
    canada: { indeedDomain: 'ca', indeedCountryCode: 'CA', glassdoorDomain: 'www.glassdoor.ca' },
    chile: { indeedDomain: 'cl', indeedCountryCode: 'CL' },
    china: { indeedDomain: 'cn', indeedCountryCode: 'CN' },
    colombia: { indeedDomain: 'co', indeedCountryCode: 'CO' },
    'costa rica': { indeedDomain: 'cr', indeedCountryCode: 'CR' },
    denmark: { indeedDomain: 'dk', indeedCountryCode: 'DK' },
    ecuador: { indeedDomain: 'ec', indeedCountryCode: 'EC' },
    egypt: { indeedDomain: 'eg', indeedCountryCode: 'EG' },
    finland: { indeedDomain: 'fi', indeedCountryCode: 'FI' },
    france: { indeedDomain: 'fr', indeedCountryCode: 'FR', glassdoorDomain: 'www.glassdoor.fr' },
    germany: { indeedDomain: 'de', indeedCountryCode: 'DE', glassdoorDomain: 'www.glassdoor.de' },
    greece: { indeedDomain: 'gr', indeedCountryCode: 'GR' },
    'hong kong': { indeedDomain: 'hk', indeedCountryCode: 'HK', glassdoorDomain: 'www.glassdoor.com.hk' },
    hungary: { indeedDomain: 'hu', indeedCountryCode: 'HU' },
    india: { indeedDomain: 'in', indeedCountryCode: 'IN', glassdoorDomain: 'www.glassdoor.co.in' },
    indonesia: { indeedDomain: 'id', indeedCountryCode: 'ID' },
    ireland: { indeedDomain: 'ie', indeedCountryCode: 'IE', glassdoorDomain: 'www.glassdoor.ie' },
    israel: { indeedDomain: 'il', indeedCountryCode: 'IL' },
    italy: { indeedDomain: 'it', indeedCountryCode: 'IT', glassdoorDomain: 'www.glassdoor.it' },
    japan: { indeedDomain: 'jp', indeedCountryCode: 'JP' },
    kuwait: { indeedDomain: 'kw', indeedCountryCode: 'KW' },
    luxembourg: { indeedDomain: 'lu', indeedCountryCode: 'LU' },
    malaysia: { indeedDomain: 'malaysia', indeedCountryCode: 'MY', glassdoorDomain: 'www.glassdoor.com' },
    mexico: { indeedDomain: 'mx', indeedCountryCode: 'MX', glassdoorDomain: 'www.glassdoor.com.mx' },
    morocco: { indeedDomain: 'ma', indeedCountryCode: 'MA' },
    netherlands: { indeedDomain: 'nl', indeedCountryCode: 'NL', glassdoorDomain: 'www.glassdoor.nl' },
    'new zealand': { indeedDomain: 'nz', indeedCountryCode: 'NZ', glassdoorDomain: 'www.glassdoor.co.nz' },
    nigeria: { indeedDomain: 'ng', indeedCountryCode: 'NG' },
    norway: { indeedDomain: 'no', indeedCountryCode: 'NO' },
    oman: { indeedDomain: 'om', indeedCountryCode: 'OM' },
    pakistan: { indeedDomain: 'pk', indeedCountryCode: 'PK' },
    panama: { indeedDomain: 'pa', indeedCountryCode: 'PA' },
    peru: { indeedDomain: 'pe', indeedCountryCode: 'PE' },
    philippines: { indeedDomain: 'ph', indeedCountryCode: 'PH' },
    poland: { indeedDomain: 'pl', indeedCountryCode: 'PL' },
    portugal: { indeedDomain: 'pt', indeedCountryCode: 'PT' },
    qatar: { indeedDomain: 'qa', indeedCountryCode: 'QA' },
    romania: { indeedDomain: 'ro', indeedCountryCode: 'RO' },
    'saudi arabia': { indeedDomain: 'sa', indeedCountryCode: 'SA' },
    singapore: { indeedDomain: 'sg', indeedCountryCode: 'SG', glassdoorDomain: 'www.glassdoor.sg' },
    'south africa': { indeedDomain: 'za', indeedCountryCode: 'ZA' },
    'south korea': { indeedDomain: 'kr', indeedCountryCode: 'KR' },
    spain: { indeedDomain: 'es', indeedCountryCode: 'ES', glassdoorDomain: 'www.glassdoor.es' },
    sweden: { indeedDomain: 'se', indeedCountryCode: 'SE' },
    switzerland: { indeedDomain: 'ch', indeedCountryCode: 'CH', glassdoorDomain: 'de.glassdoor.ch' },
    taiwan: { indeedDomain: 'tw', indeedCountryCode: 'TW' },
    thailand: { indeedDomain: 'th', indeedCountryCode: 'TH' },
    turkey: { indeedDomain: 'tr', indeedCountryCode: 'TR' },
    'türkiye': { indeedDomain: 'tr', indeedCountryCode: 'TR' },
    ukraine: { indeedDomain: 'ua', indeedCountryCode: 'UA' },
    'united arab emirates': { indeedDomain: 'ae', indeedCountryCode: 'AE' },
    uk: { indeedDomain: 'uk', indeedCountryCode: 'GB', glassdoorDomain: 'www.glassdoor.co.uk' },
    'united kingdom': { indeedDomain: 'uk', indeedCountryCode: 'GB', glassdoorDomain: 'www.glassdoor.co.uk' },
    usa: { indeedDomain: 'www', indeedCountryCode: 'US', glassdoorDomain: 'www.glassdoor.com' },
    us: { indeedDomain: 'www', indeedCountryCode: 'US', glassdoorDomain: 'www.glassdoor.com' },
    'united states': { indeedDomain: 'www', indeedCountryCode: 'US', glassdoorDomain: 'www.glassdoor.com' },
    uruguay: { indeedDomain: 'uy', indeedCountryCode: 'UY' },
    venezuela: { indeedDomain: 've', indeedCountryCode: 'VE' },
    vietnam: { indeedDomain: 'vn', indeedCountryCode: 'VN', glassdoorDomain: 'www.glassdoor.com' }
};

export function resolveJobSpyCountry(location?: string, explicitCountry?: string): JobSpyCountry {
    const value = (explicitCountry || location || 'usa').toLowerCase().trim();
    return COUNTRY_MAP[value] ?? COUNTRY_MAP[value.replace(/\s+/g, ' ')] ?? COUNTRY_MAP.usa;
}
